apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-1
          image: dhruvprajapaticode/nginx-site:v1
          ports:
            - containerPort: 80
        - name: nginx-2
          image: dhruvprajapaticode/nginx-site:v2
          ports:
            - containerPort: 8082
        - name: nginx-3
          image: dhruvprajapaticode/nginx-site:v3
          ports:
            - containerPort: 8083